services:
  referal-api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./stakewolle_api_service:/stakewolle_api_service
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py initadmin &&
      python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:latest
    container_name: postgres

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  redis:
    image: redis:latest
    hostname: redis







